version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545


  truffle:
    build:
      context: truffle
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./truffle:/src