version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545


  truffle:
    build:
      context: truffle
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' localhost:8545
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./truffle:/src